### ISSUE TITLE
qgis plugin prototype

### ISSUE THREAD

**Issue by landam** [storm-fsv-cvut/smoderp2d#18]
# Basic prototype

* Data preparation
* Interface for smoderp lib (GRASS provider will be probably used, #21 )
* Display output data

## Tasks

- [x] @kavkapet review tabs (how to split parameters)
- [x] @pesekon2 remove pickle file option
- [x] @pesekon2 new module to define labels (which will be used by QGIS, GRASS module and ArcGIS - see `bin/arcgis/SMODERP2D.pyt`  -> `getParameterInfo`)

```
key - `inputSurfaceRaster`
label - _("Input surface raster")
label_cs - ?
section - None | "Settings"
data_type: raster | vector | column | int | float
tooltip: read from ArcGIS file
```

- [x] @kavkapet design soil tables (predefined tables)
- [x] @kavkapet which output data display (+ symbology)

Question: how to deal with localization?

# Improvements

* Graphs
* ... ?

**Comment by landam** [comment]
@kavkapet ...

![Screenshot from 2023-04-17 15-10-55](https://user-images.githubusercontent.com/5683186/232503829-5351e87c-6342-4c17-83af-98b152d41435.png)

![Screenshot from 2023-04-17 15-11-02](https://user-images.githubusercontent.com/5683186/232503851-dcc4006b-1e2d-41a8-abad-7604d0e411cf.png)

![Screenshot from 2023-04-17 15-11-06](https://user-images.githubusercontent.com/5683186/232503861-bcce019e-e928-409f-9ecb-1dc36f8f9bc5.png)

**Comment by landam** [comment]
Basic prototype of QGIS plugin is available in git.
